version: '3.7'

services:
  zookeeper-01:
    image: confluentinc/cp-zookeeper:7.5.3
    restart: always
    hostname: zookeeper-01
    container_name: zookeeper-01
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
    networks:
      - tasksmart-network

  zookeeper-02:
    image: confluentinc/cp-zookeeper:7.5.3
    restart: always
    hostname: zookeeper-02
    container_name: zookeeper-02
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
    networks:
      - tasksmart-network

  zookeeper-03:
    image: confluentinc/cp-zookeeper:7.5.3
    restart: always
    hostname: zookeeper-03
    container_name: zookeeper-03
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
    networks:
      - tasksmart-network

  kafka-broker-01:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka-broker-01
    container_name: kafka-broker-01
    ports:
      - "9092:9092" #Cho phep truy cap giao tiep client -> kafka : 9092
      - "29092:29092" #Cho phep giao tiep giua cac broker kafka trong cluster
      - "9999:9999" #Cho phep truy cap JMX
    environment:
      #Dinh nghia cac listener cho kafka
      #INTERNAL: kafka-broker-01:19092: cho phep cac broker kafka container noi bo giao tiep voi nhau
      #EXTERNAL: ${DOCKER_HOST_IP:-127.0.1}:9092: cho phep cac client ben ngoai giao tiep voi kafka qua port 9092
      #DOCKER: host.docker.internal:29092:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-01:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092

      #Thiet lap giai thuc bao mat cho tung listener, dung plantext => ko ma hoa
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT

      #Thiet lap listener dung cho giao tiep giua cac broker trong kafka
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-01:2181,zookeeper-02:2182,zookeeper-03:2183"
      KAFKA_BROKER_ID: 1

      #Cau hinh log level
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer

      #Thiet lap so rep
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #Thiet lap transaction_state_log
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      #Thiet lap so broker toi thieu de commit transaction
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - tasksmart-network
    depends_on:
      - zookeeper-01
      - zookeeper-02
      - zookeeper-03

  kafka-broker-02:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka-broker-02
    container_name: kafka-broker-02
    ports:
      - "9093:9093" #Cho phep truy cap giao tiep client -> kafka : 9092
      - "29093:29093" #Cho phep giao tiep giua cac broker kafka trong cluster
    environment:
      #Dinh nghia cac listener cho kafka
      #INTERNAL: kafka-broker-01:19092: cho phep cac broker kafka container noi bo giao tiep voi nhau
      #EXTERNAL: ${DOCKER_HOST_IP:-127.0.1}:9092: cho phep cac client ben ngoai giao tiep voi kafka qua port 9092
      #DOCKER: host.docker.internal:29092:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-01:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.1}:9093,DOCKER://host.docker.internal:29093

      #Thiet lap giai thuc bao mat cho tung listener, dung plantext => ko ma hoa
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT

      #Thiet lap listener dung cho giao tiep giua cac broker trong kafka
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181,zookeeper-02:2182,zookeeper-03:2183
      KAFKA_BROKER_ID: 1

      #Cau hinh log level
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - tasksmart-network
    depends_on:
      - zookeeper-01
      - zookeeper-02
      - zookeeper-03
networks:
    tasksmart-network:
        driver: bridge
        name: tasksmart-network
