package com.tasksmart.sharedLibrary.models.enums;

public enum EActivityType {
    CREATE_WORKSPACE,
    UPDATE_WORKSPACE,
    USER_JOIN_WORKSPACE,
    USER_LEAVE_WORKSPACE,

    ACCESS_PROJECT,
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    USER_JOIN_PROJECT,
    USER_LEAVE_PROJECT,

    CREATE_LIST_CARD,
    UPDATE_LIST_CARD,
    DELETE_LIST_CARD,

    CREATE_CARD,
    UPDATE_CARD,
    DELETE_CARD,
    UPDATE_USER_MEMBER

}
